id: 505e89498b9e41d8a00cb720f4519f2e
initial_creation_type: ocr
source_metadata:
  volumes:
    c46f6fa9dfc046a182e577a9b60d88b8:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
